// Template: Base Controller (ApiControllerBase.t4) version 3.0

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Http;
using System.Web.Http.Description;
using CoffeeShopApi.CoffeeShopApiRaml.Models;

// Do not modify this file. This code was generated by RAML Web Api 2 Scaffolder

namespace CoffeeShopApi.CoffeeShopApiRaml
{
    [RoutePrefix("menuitems")]
    public partial class MenuitemsController : ApiController
    {


        /// <summary>
		/// All Menu Items
		/// </summary>
		/// <returns>IList&lt;MenuitemsGetOKResponseContent&gt;</returns>
        [ResponseType(typeof(IList<MenuitemsGetOKResponseContent>))]
        [HttpGet]
        [Route("")]
        public virtual IHttpActionResult GetBase()
        {
            // Do not modify this code
            return  ((IMenuitemsController)this).Get();
        }

        /// <summary>
		/// Create a new menu item.
		/// </summary>
		/// <param name="menuitemspostrequestcontent"></param>
		/// <returns>MenuitemsPostOKResponseContent</returns>
        [ResponseType(typeof(MenuitemsPostOKResponseContent))]
        [HttpPost]
        [Route("")]
        public virtual IHttpActionResult PostBase(Models.MenuitemsPostRequestContent menuitemspostrequestcontent)
        {
            // Do not modify this code
            return  ((IMenuitemsController)this).Post(menuitemspostrequestcontent);
        }

        /// <summary>
		/// A specific menu item
		/// </summary>
		/// <param name="itemId">The id of the requested item</param>
		/// <returns>MenuitemsItemIdGetOKResponseContent</returns>
        [ResponseType(typeof(MenuitemsItemIdGetOKResponseContent))]
        [HttpGet]
        [Route("{itemId}")]
        public virtual IHttpActionResult GetByItemIdBase([FromUri] string itemId)
        {
            // Do not modify this code
            return  ((IMenuitemsController)this).GetByItemId(itemId);
        }

        /// <summary>
		/// Update a specific menu item
		/// </summary>
		/// <param name="menuitemsitemidputrequestcontent"></param>
		/// <param name="itemId">The id of the requested item</param>
        [HttpPut]
        [Route("{itemId}")]
        public virtual IHttpActionResult PutBase(Models.MenuitemsItemIdPutRequestContent menuitemsitemidputrequestcontent,[FromUri] string itemId)
        {
            // Do not modify this code
            return  ((IMenuitemsController)this).Put(menuitemsitemidputrequestcontent,itemId);
        }

        /// <summary>
		/// Remove a specific menu item
		/// </summary>
		/// <param name="itemId">The id of the requested item</param>
        [HttpDelete]
        [Route("{itemId}")]
        public virtual IHttpActionResult DeleteBase([FromUri] string itemId)
        {
            // Do not modify this code
            return  ((IMenuitemsController)this).Delete(itemId);
        }
    }
}
