// Template: Models (ApiModel.t4) version 3.0

// This code was generated by RAML Web Api 2 Scaffolder

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace CoffeeShopApi.CoffeeShopApiRaml.Models
{
    public partial class Orders0
    {
        

        /// <summary>
        /// Position in pagination
        /// </summary>

		[JsonProperty("offset")]
        public int? Offset { get; set; }

        /// <summary>
        /// Number of items to retrieve (10 max).
        /// </summary>

		[JsonProperty("limit")]
        public int? Limit { get; set; }

        /// <summary>
        /// Total number of items available
        /// </summary>

		[JsonProperty("count")]
        public int? Count { get; set; }


		[JsonProperty("orders")]
        public IList<Orders> Orders { get; set; }
    } // end class

} // end Models namespace

